# Generated by Django 3.0.8 on 2021-02-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210211_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Общая цена'),
        ),
    ]
